# Generated by Django 2.2.4 on 2019-08-13 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('date_start', models.DateTimeField(verbose_name='Inicio da atividade')),
                ('date_end', models.DateTimeField(verbose_name='Fim da atividade')),
                ('professional', models.CharField(max_length=100, verbose_name='Profissional')),
                ('vacancies', models.IntegerField(default=1, verbose_name='Vagas')),
                ('workload', models.IntegerField(default=1, verbose_name='Carga horária')),
                ('description', models.CharField(max_length=300, verbose_name='Descriçao')),
                ('time_tables', models.CharField(max_length=300, verbose_name='Tabela de Horários')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('date_start', models.DateTimeField(verbose_name='Data de Inicio')),
                ('date_end', models.DateTimeField(verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo ')),
                ('edition', models.CharField(max_length=100, verbose_name='Edição')),
                ('start_of_registrations', models.DateField(verbose_name='Inicio das Incrições')),
                ('end_of_registrations', models.DateField(verbose_name='Fim das Incrições')),
                ('qtd_max_authors', models.IntegerField(default=1, verbose_name='Quantide máxima de autores')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Campus', verbose_name='Campus ')),
                ('organizers', models.ManyToManyField(blank=True, related_name='editions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('status', models.BooleanField(default=False, verbose_name='Status da inscrição')),
                ('date_of_inscription', models.DateTimeField(verbose_name='Data de Inscrição')),
                ('present', models.BooleanField(default=False, verbose_name='Presente ')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Edition', verbose_name='Edicao')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Local')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de Atividade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InscriptionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('status', models.BooleanField(default=False, verbose_name='Status da inscrição')),
                ('date_of_inscription', models.DateTimeField(verbose_name='Data de Inscrição')),
                ('present', models.BooleanField(default=False, verbose_name='Presente ')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Activity', verbose_name='Atividade')),
                ('inscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Inscription', verbose_name='Atividade')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivityTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Autalizado em')),
                ('date_start', models.TimeField(verbose_name='Data de inicio')),
                ('date_end', models.TimeField(verbose_name='Data de fim')),
                ('date', models.DateField(verbose_name='Data')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Activity', verbose_name='Atividade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Edition', verbose_name='Edição'),
        ),
        migrations.AddField(
            model_name='activity',
            name='type_of_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.TypeActivity', verbose_name='Tipo de atividade'),
        ),
    ]
