# Generated by Django 2.2.4 on 2019-09-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_auto_20190824_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='date_start',
        ),
    ]
