# Generated by Django 2.2.4 on 2019-09-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0003_auto_20190908_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='time_tables',
        ),
    ]
