# Generated by Django 2.2.4 on 2019-09-19 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0004_remove_activity_time_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Campus', verbose_name='Campus '),
        ),
        migrations.AlterField(
            model_name='edition',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo '),
        ),
        migrations.RemoveField(
            model_name='edition',
            name='campus',
        ),
        migrations.AddField(
            model_name='edition',
            name='campus',
            field=models.ManyToManyField(blank=True, null=True, related_name='campus', to='editions.Campus', verbose_name='Campus '),
        ),
    ]
