# Generated by Django 2.2.4 on 2019-09-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0005_auto_20190918_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='campus',
            field=models.ManyToManyField(blank=True, related_name='campus', to='editions.Campus', verbose_name='Campus '),
        ),
    ]
