# Generated by Django 2.2.4 on 2019-09-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0006_auto_20190918_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Campus', verbose_name='Campus '),
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editions.Location', verbose_name='lugar'),
        ),
    ]
