# Generated by Django 2.2.4 on 2019-09-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0005_auto_20190919_1419'),
        ('editions', '0007_auto_20190918_2314'),
    ]

    operations = [
    ]
