# Generated by Django 2.2.4 on 2019-10-25 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0008_merge_20190920_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='end_activity',
            field=models.DateField(default=datetime.date(2019, 10, 25), verbose_name='Fim das Incrições nas Atividades'),
        ),
        migrations.AddField(
            model_name='edition',
            name='start_activity',
            field=models.DateField(default=datetime.date(2019, 10, 25), verbose_name='Inicio das Incrições nas Atividades'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='date_end',
            field=models.DateTimeField(verbose_name='Data de Fim do Edição'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='date_start',
            field=models.DateTimeField(verbose_name='Data de Inicio da Edição'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='end_of_registrations',
            field=models.DateField(verbose_name='Fim das Incrições Nesta Edição'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='start_of_registrations',
            field=models.DateField(verbose_name='Inicio das Incrições Nesta Edição'),
        ),
    ]
