# Generated by Django 2.2.4 on 2019-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0011_auto_20191026_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='end_submissions',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das Submissões de Trabalhos'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='start_submissions',
            field=models.DateField(blank=True, null=True, verbose_name='Inicio das Submissões de Trabalhos'),
        ),
    ]
